#!/bin/bash -l
#SBATCH --parsable
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 8
#SBATCH --gres=gpu:1
#SBATCH --partition GPU_2080Ti


REMOTE_ROOT=/home/dongdong/wyz/rid-kit/examples/test_ala_drop/iter.000000/01.resMD/
echo 0 > $REMOTE_ROOT/0d0dddb5065c03b100072532f53791d2e3369e8f_flag_if_job_task_fail
test $? -ne 0 && exit 1







cd $REMOTE_ROOT
cd 001.000012
test $? -ne 0 && exit 1
if [ ! -f 439dce39705edfe08243470bc38aea585fe6604d_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch 439dce39705edfe08243470bc38aea585fe6604d_task_tag_finished; else echo 1 > $REMOTE_ROOT/0d0dddb5065c03b100072532f53791d2e3369e8f_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000937
test $? -ne 0 && exit 1
if [ ! -f dd75ad59c1ff3400cde8f933d5c7bcb400131653_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch dd75ad59c1ff3400cde8f933d5c7bcb400131653_task_tag_finished; else echo 1 > $REMOTE_ROOT/0d0dddb5065c03b100072532f53791d2e3369e8f_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000862
test $? -ne 0 && exit 1
if [ ! -f 20dde2858c4172a08876962dfc938d161b222663_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch 20dde2858c4172a08876962dfc938d161b222663_task_tag_finished; else echo 1 > $REMOTE_ROOT/0d0dddb5065c03b100072532f53791d2e3369e8f_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 001.000738
test $? -ne 0 && exit 1
if [ ! -f 41eb94cfba8333a3d6b96fb2de7347fbafe6876d_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch 41eb94cfba8333a3d6b96fb2de7347fbafe6876d_task_tag_finished; else echo 1 > $REMOTE_ROOT/0d0dddb5065c03b100072532f53791d2e3369e8f_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 001.000713
test $? -ne 0 && exit 1
if [ ! -f c1d86edae6edf73118ff465029f535a079b80898_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch c1d86edae6edf73118ff465029f535a079b80898_task_tag_finished; else echo 1 > $REMOTE_ROOT/0d0dddb5065c03b100072532f53791d2e3369e8f_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000450
test $? -ne 0 && exit 1
if [ ! -f 61ca8f1ee258bb59628920dfdf643a6419adc06c_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch 61ca8f1ee258bb59628920dfdf643a6419adc06c_task_tag_finished; else echo 1 > $REMOTE_ROOT/0d0dddb5065c03b100072532f53791d2e3369e8f_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000416
test $? -ne 0 && exit 1
if [ ! -f 4649789aaf1c5ad2a9e8c40e9ddb726b38acf763_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch 4649789aaf1c5ad2a9e8c40e9ddb726b38acf763_task_tag_finished; else echo 1 > $REMOTE_ROOT/0d0dddb5065c03b100072532f53791d2e3369e8f_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000885
test $? -ne 0 && exit 1
if [ ! -f c0628849dc39941bf5248695c3267dc4e1a73a73_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch c0628849dc39941bf5248695c3267dc4e1a73a73_task_tag_finished; else echo 1 > $REMOTE_ROOT/0d0dddb5065c03b100072532f53791d2e3369e8f_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000883
test $? -ne 0 && exit 1
if [ ! -f a59f6428e3ec81895105dd12e45b7c5ba95adde8_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch a59f6428e3ec81895105dd12e45b7c5ba95adde8_task_tag_finished; else echo 1 > $REMOTE_ROOT/0d0dddb5065c03b100072532f53791d2e3369e8f_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000974
test $? -ne 0 && exit 1
if [ ! -f 50dbb8bf691d4eacd7b53c03ec2196cc39bf3a29_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch 50dbb8bf691d4eacd7b53c03ec2196cc39bf3a29_task_tag_finished; else echo 1 > $REMOTE_ROOT/0d0dddb5065c03b100072532f53791d2e3369e8f_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 0d0dddb5065c03b100072532f53791d2e3369e8f_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 0d0dddb5065c03b100072532f53791d2e3369e8f_job_tag_finished; else exit 1;fi

