#!/bin/bash -l
#SBATCH --parsable
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 8
#SBATCH --gres=gpu:1
#SBATCH --partition GPU_2080Ti


REMOTE_ROOT=/home/dongdong/wyz/rid-kit/examples/test_ala_drop/iter.000000/01.resMD/
echo 0 > $REMOTE_ROOT/ab2ca702f560bd8a9513fce296ffa325fcfb8d6e_flag_if_job_task_fail
test $? -ne 0 && exit 1







cd $REMOTE_ROOT
cd 001.000975
test $? -ne 0 && exit 1
if [ ! -f 3e783ea772d34767816d091ad6b7f87ad3968cc7_task_tag_finished ] ;then
   ( gmx grompp -maxwarn 1 1> gmx_grompp.log 2> gmx_grompp.log ) 1>>gmx_grompp.log 2>>gmx_grompp.log 
  if test $? -eq 0; then touch 3e783ea772d34767816d091ad6b7f87ad3968cc7_task_tag_finished; else echo 1 > $REMOTE_ROOT/ab2ca702f560bd8a9513fce296ffa325fcfb8d6e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000335
test $? -ne 0 && exit 1
if [ ! -f 1d5edf4218f12c7deaddb9aa0cdeb9a57a2667b4_task_tag_finished ] ;then
   ( gmx grompp -maxwarn 1 1> gmx_grompp.log 2> gmx_grompp.log ) 1>>gmx_grompp.log 2>>gmx_grompp.log 
  if test $? -eq 0; then touch 1d5edf4218f12c7deaddb9aa0cdeb9a57a2667b4_task_tag_finished; else echo 1 > $REMOTE_ROOT/ab2ca702f560bd8a9513fce296ffa325fcfb8d6e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 001.000800
test $? -ne 0 && exit 1
if [ ! -f ffc2253cd53adb0a1a58980fe93a948a4de3985d_task_tag_finished ] ;then
   ( gmx grompp -maxwarn 1 1> gmx_grompp.log 2> gmx_grompp.log ) 1>>gmx_grompp.log 2>>gmx_grompp.log 
  if test $? -eq 0; then touch ffc2253cd53adb0a1a58980fe93a948a4de3985d_task_tag_finished; else echo 1 > $REMOTE_ROOT/ab2ca702f560bd8a9513fce296ffa325fcfb8d6e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000649
test $? -ne 0 && exit 1
if [ ! -f 6a7d0dcffd4c312232b5e1bffffe2495f43479e9_task_tag_finished ] ;then
   ( gmx grompp -maxwarn 1 1> gmx_grompp.log 2> gmx_grompp.log ) 1>>gmx_grompp.log 2>>gmx_grompp.log 
  if test $? -eq 0; then touch 6a7d0dcffd4c312232b5e1bffffe2495f43479e9_task_tag_finished; else echo 1 > $REMOTE_ROOT/ab2ca702f560bd8a9513fce296ffa325fcfb8d6e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000807
test $? -ne 0 && exit 1
if [ ! -f 5c2e80de87e6f2bc4a0c7fdb83e55136e537b107_task_tag_finished ] ;then
   ( gmx grompp -maxwarn 1 1> gmx_grompp.log 2> gmx_grompp.log ) 1>>gmx_grompp.log 2>>gmx_grompp.log 
  if test $? -eq 0; then touch 5c2e80de87e6f2bc4a0c7fdb83e55136e537b107_task_tag_finished; else echo 1 > $REMOTE_ROOT/ab2ca702f560bd8a9513fce296ffa325fcfb8d6e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 001.000787
test $? -ne 0 && exit 1
if [ ! -f 39715da6bca26932ae5a6e24c08391bd3b3242c4_task_tag_finished ] ;then
   ( gmx grompp -maxwarn 1 1> gmx_grompp.log 2> gmx_grompp.log ) 1>>gmx_grompp.log 2>>gmx_grompp.log 
  if test $? -eq 0; then touch 39715da6bca26932ae5a6e24c08391bd3b3242c4_task_tag_finished; else echo 1 > $REMOTE_ROOT/ab2ca702f560bd8a9513fce296ffa325fcfb8d6e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000042
test $? -ne 0 && exit 1
if [ ! -f 46c1a0cdac695728d79434dbbfd7048fa1bc9ba5_task_tag_finished ] ;then
   ( gmx grompp -maxwarn 1 1> gmx_grompp.log 2> gmx_grompp.log ) 1>>gmx_grompp.log 2>>gmx_grompp.log 
  if test $? -eq 0; then touch 46c1a0cdac695728d79434dbbfd7048fa1bc9ba5_task_tag_finished; else echo 1 > $REMOTE_ROOT/ab2ca702f560bd8a9513fce296ffa325fcfb8d6e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000280
test $? -ne 0 && exit 1
if [ ! -f 25d2b86b8d6a5ffb403c3840c3405488f7cda467_task_tag_finished ] ;then
   ( gmx grompp -maxwarn 1 1> gmx_grompp.log 2> gmx_grompp.log ) 1>>gmx_grompp.log 2>>gmx_grompp.log 
  if test $? -eq 0; then touch 25d2b86b8d6a5ffb403c3840c3405488f7cda467_task_tag_finished; else echo 1 > $REMOTE_ROOT/ab2ca702f560bd8a9513fce296ffa325fcfb8d6e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 001.000669
test $? -ne 0 && exit 1
if [ ! -f 35a851bf0e7b3129ecb64a566941232481df5dfc_task_tag_finished ] ;then
   ( gmx grompp -maxwarn 1 1> gmx_grompp.log 2> gmx_grompp.log ) 1>>gmx_grompp.log 2>>gmx_grompp.log 
  if test $? -eq 0; then touch 35a851bf0e7b3129ecb64a566941232481df5dfc_task_tag_finished; else echo 1 > $REMOTE_ROOT/ab2ca702f560bd8a9513fce296ffa325fcfb8d6e_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat ab2ca702f560bd8a9513fce296ffa325fcfb8d6e_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch ab2ca702f560bd8a9513fce296ffa325fcfb8d6e_job_tag_finished; else exit 1;fi

