#!/bin/bash -l
#SBATCH --parsable
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 8
#SBATCH --gres=gpu:1
#SBATCH --partition GPU_2080Ti


REMOTE_ROOT=/home/dongdong/wyz/rid-kit/examples/test_ala_drop/iter.000000/01.resMD/
echo 0 > $REMOTE_ROOT/ca417ffdae381a6dc5da27e1cd14e7c1b519ca1e_flag_if_job_task_fail
test $? -ne 0 && exit 1







cd $REMOTE_ROOT
cd 000.000859
test $? -ne 0 && exit 1
if [ ! -f 5372b391be4bc39b50a48ab8ecb6f8924bbb2910_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch 5372b391be4bc39b50a48ab8ecb6f8924bbb2910_task_tag_finished; else echo 1 > $REMOTE_ROOT/ca417ffdae381a6dc5da27e1cd14e7c1b519ca1e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 001.000795
test $? -ne 0 && exit 1
if [ ! -f b110853c204af74a0e3a57e34be6c16d3dd34ece_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch b110853c204af74a0e3a57e34be6c16d3dd34ece_task_tag_finished; else echo 1 > $REMOTE_ROOT/ca417ffdae381a6dc5da27e1cd14e7c1b519ca1e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 001.000634
test $? -ne 0 && exit 1
if [ ! -f 37e87926d2c9fe8568e73b4ed5384919741b8fce_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch 37e87926d2c9fe8568e73b4ed5384919741b8fce_task_tag_finished; else echo 1 > $REMOTE_ROOT/ca417ffdae381a6dc5da27e1cd14e7c1b519ca1e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 001.000978
test $? -ne 0 && exit 1
if [ ! -f 754245a0e9776fc0cd1371ace7fc8bc6bdc14375_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch 754245a0e9776fc0cd1371ace7fc8bc6bdc14375_task_tag_finished; else echo 1 > $REMOTE_ROOT/ca417ffdae381a6dc5da27e1cd14e7c1b519ca1e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000977
test $? -ne 0 && exit 1
if [ ! -f 863d6d3de005e35526fb1e816b39c3c6a7c163d8_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch 863d6d3de005e35526fb1e816b39c3c6a7c163d8_task_tag_finished; else echo 1 > $REMOTE_ROOT/ca417ffdae381a6dc5da27e1cd14e7c1b519ca1e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 001.000864
test $? -ne 0 && exit 1
if [ ! -f d7fc8051cb14cb0a7464cb2181c0378117110578_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch d7fc8051cb14cb0a7464cb2181c0378117110578_task_tag_finished; else echo 1 > $REMOTE_ROOT/ca417ffdae381a6dc5da27e1cd14e7c1b519ca1e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000128
test $? -ne 0 && exit 1
if [ ! -f 27f7c8c2b4e04ad029e11e33c62ffd9edd737d08_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch 27f7c8c2b4e04ad029e11e33c62ffd9edd737d08_task_tag_finished; else echo 1 > $REMOTE_ROOT/ca417ffdae381a6dc5da27e1cd14e7c1b519ca1e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000933
test $? -ne 0 && exit 1
if [ ! -f 8cbfc3c08dbdfe34b33b160055312f7d43354e57_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch 8cbfc3c08dbdfe34b33b160055312f7d43354e57_task_tag_finished; else echo 1 > $REMOTE_ROOT/ca417ffdae381a6dc5da27e1cd14e7c1b519ca1e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 000.000207
test $? -ne 0 && exit 1
if [ ! -f 945126b45eef128c57af7711ce6da03635997f2b_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch 945126b45eef128c57af7711ce6da03635997f2b_task_tag_finished; else echo 1 > $REMOTE_ROOT/ca417ffdae381a6dc5da27e1cd14e7c1b519ca1e_flag_if_job_task_fail;fi
fi &
wait 

cd $REMOTE_ROOT
cd 001.000000
test $? -ne 0 && exit 1
if [ ! -f 65dfe6f909cb959df80670799e29e5e4648be6d1_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.res.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch 65dfe6f909cb959df80670799e29e5e4648be6d1_task_tag_finished; else echo 1 > $REMOTE_ROOT/ca417ffdae381a6dc5da27e1cd14e7c1b519ca1e_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat ca417ffdae381a6dc5da27e1cd14e7c1b519ca1e_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch ca417ffdae381a6dc5da27e1cd14e7c1b519ca1e_job_tag_finished; else exit 1;fi

