#!/bin/bash -l
#SBATCH --parsable
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 8
#SBATCH --gres=gpu:1
#SBATCH --partition GPU_2080Ti


REMOTE_ROOT=/home/dongdong/wyz/rid-kit/examples/test_ala_drop/iter.000000/00.enhcMD/
echo 0 > $REMOTE_ROOT/2d9edb6b52cdfa22702b63aa62aeec9b08fc5043_flag_if_job_task_fail
test $? -ne 0 && exit 1







cd $REMOTE_ROOT
cd 000
test $? -ne 0 && exit 1
if [ ! -f 92947b78f2ab2fe9218610e473aafdc7c41f3a7f_task_tag_finished ] ;then
   ( gmx grompp -maxwarn 1 1> gmx_grompp.log 2> gmx_grompp.log ) 1>>gmx_grompp.log 2>>gmx_grompp.log 
  if test $? -eq 0; then touch 92947b78f2ab2fe9218610e473aafdc7c41f3a7f_task_tag_finished; else echo 1 > $REMOTE_ROOT/2d9edb6b52cdfa22702b63aa62aeec9b08fc5043_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 2d9edb6b52cdfa22702b63aa62aeec9b08fc5043_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 2d9edb6b52cdfa22702b63aa62aeec9b08fc5043_job_tag_finished; else exit 1;fi

