#!/bin/bash -l
#SBATCH --parsable
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 8
#SBATCH --gres=gpu:1
#SBATCH --partition GPU_2080Ti


REMOTE_ROOT=/home/dongdong/wyz/rid-kit/examples/test_ala_drop/iter.000000/00.enhcMD/
echo 0 > $REMOTE_ROOT/374e1139ad777825909f21f071d9ad0e7301934d_flag_if_job_task_fail
test $? -ne 0 && exit 1







cd $REMOTE_ROOT
cd 001
test $? -ne 0 && exit 1
if [ ! -f 43675a224011368a981d5473c9d1d7fef097788b_task_tag_finished ] ;then
   ( gmx grompp -maxwarn 1 1> gmx_grompp.log 2> gmx_grompp.log ) 1>>gmx_grompp.log 2>>gmx_grompp.log 
  if test $? -eq 0; then touch 43675a224011368a981d5473c9d1d7fef097788b_task_tag_finished; else echo 1 > $REMOTE_ROOT/374e1139ad777825909f21f071d9ad0e7301934d_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 374e1139ad777825909f21f071d9ad0e7301934d_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 374e1139ad777825909f21f071d9ad0e7301934d_job_tag_finished; else exit 1;fi

