#!/bin/bash -l
#SBATCH --parsable
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 8
#SBATCH --gres=gpu:1
#SBATCH --partition GPU_2080Ti


REMOTE_ROOT=/home/dongdong/wyz/rid-kit/examples/test_ala_drop/iter.000000/00.enhcMD/
echo 0 > $REMOTE_ROOT/db04bf79486be3ee3d1002aa410bda8f9bbd4fb6_flag_if_job_task_fail
test $? -ne 0 && exit 1







cd $REMOTE_ROOT
cd 000
test $? -ne 0 && exit 1
if [ ! -f cff62248daacacece978687bf28e48253a4ddb04_task_tag_finished ] ;then
   ( gmx mdrun -ntmpi 1 -nt 8 -plumed plumed.bf.dat 1> gmx_mdrun.log 2> gmx_mdrun.log ) 1>>gmx_mdrun.log 2>>gmx_mdrun.log 
  if test $? -eq 0; then touch cff62248daacacece978687bf28e48253a4ddb04_task_tag_finished; else echo 1 > $REMOTE_ROOT/db04bf79486be3ee3d1002aa410bda8f9bbd4fb6_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat db04bf79486be3ee3d1002aa410bda8f9bbd4fb6_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch db04bf79486be3ee3d1002aa410bda8f9bbd4fb6_job_tag_finished; else exit 1;fi

