#!/bin/bash -l
#SBATCH --parsable
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 4
#SBATCH --gres=gpu:0
#SBATCH --partition GPU_2080Ti


REMOTE_ROOT=/home/dongdong/wyz/rid-kit/examples/test_ala_drop/iter.000000/00.enhcMD/
echo 0 > $REMOTE_ROOT/e8fcba8be75f3d523a6dcf4d324e08db097bb69b_flag_if_job_task_fail
test $? -ne 0 && exit 1







cd $REMOTE_ROOT
cd 000
test $? -ne 0 && exit 1
if [ ! -f b82ac59f59bf79b7b9d8995cee51deec5aaf80fd_task_tag_finished ] ;then
   ( echo 0 | gmx trjconv -sep -f traj.trr -o confs/conf.gro -vel 1> gmx_split.log 2> gmx_split.log ) 1>>gmx_split.log 2>>gmx_split.log 
  if test $? -eq 0; then touch b82ac59f59bf79b7b9d8995cee51deec5aaf80fd_task_tag_finished; else echo 1 > $REMOTE_ROOT/e8fcba8be75f3d523a6dcf4d324e08db097bb69b_flag_if_job_task_fail;fi
fi &
wait 


cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat e8fcba8be75f3d523a6dcf4d324e08db097bb69b_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch e8fcba8be75f3d523a6dcf4d324e08db097bb69b_job_tag_finished; else exit 1;fi

