name: rid python package test

on:
  - push
  - pull_request

jobs:
  Unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup package
      run: |
        echo "test"
    - name: Run unittest
      run: |
        echo "test"
