name: rid python package test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.6
    - name: Setup package
      run: |
          echo $PATH
          pwd

#         wget https://github.com/Dead-fisher/rid-kit/releases/download/v1.0/gromacs-dp-rid-0.0.5-float-gpu-Linux-x86_64.sh
#         sh gromacs-dp-rid-0.0.5-float-gpu-Linux-x86_64.sh

#         pip install numpy
#         pip install sklearn
#         pip install dpdispatcher
#         pip insta
#     - run: |
#         cd ./tests
#         python -m unittest
#     - run: python test_cal_cv.py
#     - run: python test_gen_rid.py
#     - run: python test_lib_gen.py
#     - run: python test_lib_machine.py
#     - run: python test_lib_make.py
#     - run: python test_lib_std.py
#     - run: python test_lib_utils.py
#     - run: python test_make_enhc.py
#     - run: python test_make_res.py
#     - run: python test_make_train.py
#     - run: python test_post_enhc.py
#     - run: python test_post_res.py
#     - run: python test_run_enhc.py
#     - run: python test_run_res.py
#     - run: python test_run_train.py
