# /home/runner/work/rid-kit/rid-kit
name: rid python package test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup package
      run: |
          wget -q https://github.com/Dead-fisher/rid-kit/releases/download/v1.0/gromacs-dp-rid-0.0.5-float-gpu-Linux-x86_64.sh > download.log
          sh gromacs-dp-rid-0.0.5-float-gpu-Linux-x86_64.sh
          ls
          rid_bin=$(pwd)/gromacs-dp-rid/bin
          export PATH="$rid_bin:$PATH"
          which python
          pip install numpy
          pip install sklearn
          pip install dpdispatcher
          pip install mock
    - name: Run unittest
      run: |
        cd ./tests
        python -m unittest
